name: kelana_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter:
    sdk: flutter
  velocity_x: ^3.5.1
  get_storage: ^2.0.3
  bottom_navy_bar: ^6.0.0
  animated_icon_button: ^1.0.2
  cached_network_image: ^3.2.1
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
